Epidaurus/ViewModels/MovieViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Epidaurus.Domain.Entities;

namespace Epidaurus.ViewModels
{
}

Epidaurus/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using System.Configuration;
using Epidaurus.Domain;
using Epidaurus.Domain.Entities;
using Epidaurus.ScannerLib;
using Epidaurus.ScannerLib.Imdb;
using Epidaurus.ScannerLib.Utils;
using sysIO=System.IO;
using System.Net;
using System.Linq.Expressions;
using Epidaurus.ViewModels;
using System.Diagnostics;
using Epidaurus.Security;
using System.IO;
using Epidaurus.ScannerLib.Tmdb;
using System.Data.Objects;
using Epidaurus.Domain.Mime;

namespace Epidaurus.Controllers
{
    public class MovieController : Controller
    {
        private static readonly NLog.Logger _log = NLog.LogManager.GetCurrentClassLogger();
        private readonly MovieSystemService _movieSystemService;
        private readonly MovieInformationUpdater _movieInformationUpdater;
        private readonly IMimeTypeResolver _mimeTypeResolver;

        public MovieController(MovieSystemService movieSystemService, MovieInformationUpdater movieInformationUpdater, IMimeTypeResolver mimeTypeResolver)
        {
            _movieSystemService = movieSystemService;
            _movieInformationUpdater = movieInformationUpdater;
            _mimeTypeResolver = mimeTypeResolver;
        }

        // GET: /Movie/
        [Authorize]
        public ActionResult Index(MovieFilterViewModel mi)
        {
            var db = _movieSystemService.DbEntities;
            //db.ObjectStateManager.
            var vm = CreateMovieListViewModel(mi);
            var movies = MoviesWithReferences;
            ((ObjectQuery<Movie>)movies).MergeOption = MergeOption.NoTracking;

            movies = movies.Where(m => m.MovieAtStorages.Any(mas => !mas.Ignore));

            if (!string.IsNullOrEmpty(mi.Search))
                movies = movies.Where(e => e.Title.Contains(mi.Search) || e.MovieAtStorages.Any(mas=>mas.CleanedName.Contains(mi.Search)));

            if (mi.Person.HasValue)
                movies = movies.Where(m => m.Casts.Any(c => c.PersonId == mi.Person.Value));
            if (mi.Genre.HasValue)
                movies = movies.Where(e => e.Genres.Any(d => d.Id == mi.Genre.Value));

            switch (mi.SortBy.ToLowerInvariant())
            {
                case "score": movies = movies.OrderByDescending(el => el.Score).ThenBy(el=>el.Title); break;
                case "year": movies = movies.OrderByDescending(el => el.Year).ThenBy(el => el.Title); break;
                case "runtime": movies = movies.OrderBy(el => el.Runtime).ThenBy(el => el.Title); break;
                case "title": movies = movies.OrderBy(el => el.Title); break;
                case "addedat": 
                default: 
                    movies = movies.OrderByDescending(el => el.AddedAt).ThenBy(el => el.Title); break;
            }

            var sw = Stopwatch.StartNew();
            
            List<Movie> movieList = movies.ToList();

            ViewBag.DbCallTime = sw.ElapsedMilliseconds;

            if (mi.SelectedUsers != null && mi.SelectedUsers.Length > 0)
            {
                if (mi.SeenNotSeen == SeenNotSeen.NotSeen)
                {
                    var idFilter = new HashSet<int>(from user in db.Users from ss in user.SeenStatuses where mi.SelectedUsers.Contains(user.Username) select ss.Movie.Id);
                    movieList = movieList.Where(m => !idFilter.Contains(m.Id)).ToList();
                }
                else
                {
                    int selUsersCount = mi.SelectedUsers.Length;
                    var idFilter =
                        (from ug in
                                from user in db.Users from ss in user.SeenStatuses where mi.SelectedUsers.Contains(user.Username) select new { MovieId = ss.Movie.Id, Username = user.Username }
                            group ug by ug.MovieId into grp
                            where grp.Count() == selUsersCount
                            select grp.Key).ToList();
                    movieList = movieList.Where(m => idFilter.Contains(m.Id)).ToList();
                }
            }

            vm.Movies = movieList;
            var totalPlayTime = vm.Movies.Sum(el => el.Runtime);
            vm.TotalPlayTime = totalPlayTime.HasValue ? totalPlayTime.Value : 0;

            return View(vm);
        }

        [Authorize]
        public JsonResult ChangeSeenStatus(int id, bool seen)
        {
            try
            {
                _movieSystemService.GetMovieById(id).SetMySeenStatus(seen);
                return new JsonResult() { Data = "OK" };
            }
            catch (Exception ex)
            {
                _log.ErrorException("ChangeSeenStatus", ex);
                return new JsonResult { Data = "ERROR: " + ex.Message };
            }
        }

        private UserViewModel TryGetCurrentUser
        {
            get { return (UserViewModel) _movieSystemService.LoggedInUser; }
        }

        private IQueryable<Movie> MoviesWithReferences
        {
            get 
            { 
                return _movieSystemService.DbEntities.Movies
                    .Include("MovieAtStorages.StorageLocation")
                    .Include("Genres")
                    .Include("Casts.Person")
                    .AsQueryable(); 
            }
        }

        private MovieListViewModel CreateMovieListViewModel(MovieFilterViewModel mi)
        {
            var vm = new MovieListViewModel();
            vm.MovieFilter = mi ?? new MovieFilterViewModel();
            vm.CurrentUser = TryGetCurrentUser;
            vm.WhoHasSeenMovie = GetWhoHasSeenList();

            //Sort stuff
            if (string.IsNullOrEmpty(mi.SortBy))
                mi.SortBy = "addedat";

            var sli = SortSelectListItems.FirstOrDefault(el => el.Value == mi.SortBy);
            if (sli != null)
                sli.Selected = true;
            vm.SortByList = SortSelectListItems;
            //...

            vm.GenreList = GetGenreList(mi.Genre.HasValue ? mi.Genre.Value : -1);
            vm.PersonList = GetPersonList(mi.Person.HasValue ? mi.Person.Value : -1);

            vm.Users = _movieSystemService.DbEntities.Users.ToList().Select(el => (UserViewModel)el).ToList();
            return vm;
        }

        private static readonly List<SelectListItem> SortSelectListItems = 
            new List<SelectListItem>()
            {
                new SelectListItem() {Value = "title", Text = "Tittel"},
                new SelectListItem() {Value = "score", Text = "Score"},
                new SelectListItem() {Value = "year", Text = "År"},
                new SelectListItem() {Value = "runtime", Text = "Lengde"},
                new SelectListItem() {Value = "addedat", Text = "Lagt til"}
            };

        private Dictionary<int, List<string>> GetWhoHasSeenList()
        {
            var list = from el in
                           from ss in _movieSystemService.DbEntities.SeenStatuses
                           select new { MId = ss.Movie.Id, Username = ss.User.Name }
                       group el by el.MId into grp
                       select new { MovieId = grp.Key, SeenBy = grp.Select(el2=>el2.Username) };
            return list.ToDictionary(el => el.MovieId, el => el.SeenBy.ToList());
        }

        private static List<SelectListItem> _people;
        private static readonly object _peopleSync = new object();

        private List<SelectListItem> GetPersonList(int selectedItemId)
        {
            lock (_peopleSync)
            {
                if (_people == null)
                {
                    var emptyFirstItem = new List<SelectListItem>() { new SelectListItem() { Value = "", Text = "[ALLE]" } };
                    var dcount = from el in _movieSystemService.DbEntities.People 
                                 orderby el.Name 
                                 select new { Person = el, Count = el.Casts.Count() };
                    _people = emptyFirstItem.Union(from el in dcount.ToList()
                                                   select new SelectListItem()
                                                   {
                                                       Value = el.Person.Id.ToString(),
                                                       Text = string.Format("{0} ({1})", el.Person.Name, el.Count),
                                                   }).ToList();
                }
            }

            string selectedItemIdStr = selectedItemId.ToString();
            return new List<SelectListItem>(from el in _people select new SelectListItem() { Text = el.Text, Value = el.Value, Selected = el.Value == selectedItemIdStr });
        }

        private static List<SelectListItem> _genres;
        private static readonly object _genresSync = new object();
        private List<SelectListItem> GetGenreList(int selectedItemId)
        {
            lock (_genresSync)
            {
                if (_genres == null)
                {
                    var emptyFirstItem = new List<SelectListItem>() { new SelectListItem() { Value = "", Text = "[ALLE]" } };
                    var gcount = from el in _movieSystemService.DbEntities.Genres orderby el.Name select new { Genre = el, Count = el.Movies.Count() };
                    _genres = emptyFirstItem.Union(from el in gcount.ToList()
                               select new SelectListItem()
                               {
                                   Value = el.Genre.Id.ToString(),
                                   Text = string.Format("{0} ({1})", el.Genre.Name, el.Count),
                               }).ToList();
                }
            }

            string selectedItemIdStr = selectedItemId.ToString();
            return new List<SelectListItem>(from el in _genres select new SelectListItem() { Text = el.Text, Value = el.Value, Selected = el.Value == selectedItemIdStr });
        }

        [ChildActionOnly]

Epidaurus/Controllers/ToWatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Epidaurus.Domain;
using Epidaurus.Domain.Entities;
using Epidaurus.ScannerLib;
using Epidaurus.ViewModels;

namespace Epidaurus.Controllers
{
    public class ToWatchController : Controller
    {
        private static readonly NLog.Logger _log = NLog.LogManager.GetCurrentClassLogger();
        private readonly MovieSystemService _movieSystemService;
        private readonly MovieInformationUpdater _movieInformationUpdater;

        public ToWatchController(MovieSystemService mss, MovieInformationUpdater movieInformationUpdater)
        {
            _movieSystemService = mss;
            _movieInformationUpdater = movieInformationUpdater;
        }

        // GET: /ToWatch/

        [Authorize]
        public ActionResult Index()
        {
            var tmp = _movieSystemService.UsersWithToWatch as List<User>;  //FindIndex not available on IList..
            var idx = tmp.FindIndex(m => m.Username == User.Identity.Name);
            if (idx > 0)
            {
                var t = tmp[idx];
                tmp[idx] = tmp[0];
                tmp[0] = t;
            }

            IList<UserWithToWatch> ret = tmp.Select(el => new UserWithToWatch() { User = el, ToWatches = el.ToWatches.OrderBy(el2 => el2.Movie.Title).ToList() } ).ToList();

            return View(ret);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddToWatch(string imdbId, string comment)
        {
            try
            {
                var movie = _movieInformationUpdater.GetOrCreateNewMovieWithImdbId(imdbId);
                var toWatch = _movieSystemService.AddToWatch(movie.Id, comment);
                return View("MovieEntry", toWatch);
            }
            catch (Exception ex)
            {
                _log.ErrorException("AddToWatch", ex);
                return Json("error:" + ex.Message);
            }
        }

        [Authorize]
        [HttpPost]
        public JsonResult RemoveToWatch(int movieId)
        {
            try
            {
                _movieSystemService.RemoveToWatch(movieId);
                return Json("success");
            }
            catch (Exception ex)
            {
                _log.ErrorException("RemoveToWatch", ex);
                return Json("ERROR: " + ex.Message);
            }
        }
    }
}

Epidaurus/Views/Movie/GetImdbSearchResults.cshtml
@model Epidaurus.ScannerLib.Utils.SearchResult[]

@if (Model.Length == 0) {
    <h2>No results found</h2>
} else {
    <div id="imdbIdSearchResults">
        <table>
        @foreach (var item in Model) {
            <tr class="searchResult" data-imdbid="@item.Url">
                <td><a href="#" class="selectImdbId">@item.Title</a></td>
                <td class="iframecontainer" style="width: 500px">
                    <iframe src="@item.Url" width="500px" height="350px" frameborder="0"></iframe>
                </td>
            </tr>
        }
        </table>
    </div>
}

<script type="text/javascript">
    $("#imdbIdSearchResults .selectImdbId").bind("click", function () {
        var imdbid = $(this).closest(".searchResult").attr("data-imdbid");
        $(this).closest(".ui-dialog-content").dialog("close");
        document.movieSelectedMethod(imdbid);
        return false;
    });
</script>

Epidaurus/Views/Movie/Index.cshtml
@model Epidaurus.ViewModels.MovieListViewModel
@using Epidaurus.Helpers;
@using Epidaurus.Domain.Entities;
@using Epidaurus.ViewModels

@{
    ViewBag.Title = "Ze movies - " + Model.CurrentUser.Name;
    ViewBag.WhoHasSeenMovie = Model.WhoHasSeenMovie;
    ViewBag.MoviesIHaveSeen = (from el in Model.WhoHasSeenMovie where el.Value.Contains(Model.CurrentUser.Name) select el.Key).ToList();
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("Partials/SelectImdbId")
@Html.Partial("Partials/SelectTmdbId")

<div id="trailerDialog" style="display: none;"></div>

<div id="filterFormContainer">
    <h2>@Model.Movies.Count() filmer (spilletid @MH.RuntimeHelper(Model.TotalPlayTime)):</h2>

    @using (Html.BeginForm(null, null, FormMethod.Get, new { id = "filterForm" } ))
    {
        <table>
            <tr>
                <td>
                    Søk: <input type="text" name="Search" id="searchInputField" value="@Model.MovieFilter.Search" />
                    Genre: @Html.DropDownList("Genre", Model.GenreList)
                    Person: @Html.DropDownList("Person", Model.PersonList)
                    Sorter etter: @Html.DropDownList("SortBy", Model.SortByList)
                </td>
                <td rowspan="2" style="vertical-align: middle;">
                    <input type="submit" value="Oppdater" />
                </td>
            </tr>
            <tr>
                <td>
                    @{
                        var selUsers = Model.MovieFilter.SelectedUsers;
                        var selSeen = Model.MovieFilter.SeenNotSeen == Epidaurus.ViewModels.SeenNotSeen.Seen ? "checked=\"checked\"" : "";
                        var selNotSeen = Model.MovieFilter.SeenNotSeen == Epidaurus.ViewModels.SeenNotSeen.NotSeen ? "checked=\"checked\"" : "";
                    }
                    Vis kun filmer som følgende personer <input type="radio" name="SeenNotSeen" value="Seen" @selSeen/>har/<input type="radio" name="SeenNotSeen" value="NotSeen" @selNotSeen />har ikke sett:
                    @foreach (UserViewModel user in Model.Users)
                    {
                        <text>
                        <input type="checkbox" name="SelectedUsers" value="@user.Username" @if (selUsers.Any(el=>el==user.Username)) { <text>checked="true"</text> } />@user.Name
                        </text>
                    }
                </td>
            </tr>
        </table>
    }
</div>
<div id="filterFormContainerSpacing"></div>

<div id="moviesContainer">
    @foreach (var item in Model.Movies)
    {
        @Html.Partial("Partials/Movie", new MovieViewModel(item))
    }
</div>

<script type="text/javascript">
    var remove = ["Genre", "Person"];
    function ClearAllExcept(except) {
        for (var r in remove) {
            if (remove[r] == except)
                continue;
            $("#filterForm :input[name|=\"" + remove[r] + "\"]").val("");
        }
    }

    function SetFilter(fieldName, valuez) {
        ClearAllExcept(fieldName);
        var selector = "#filterForm :input[name|=\"" + fieldName + "\"]";
        $(selector).val(valuez);
        $("#filterForm").submit();
        return false;
    }

    function ShowTempText(containerId, text)
    {
        $("#" + containerId).prepend("<div style='position: absolute; top: 0; bottom: 0; left: 0; right: 0; background: white; opacity: 0.55; vertical-align: center; text-align: center; color: black; font-size: 24px;'>" + text + "</div>");
    }

    function UpdateMovie(movieId, container) {
        ShowTempText(container, "Wait...");
        $.ajax({
            url : "@Url.Action("UpdateMovie")" + "/" + movieId,
            type : "POST",
            success : function (data) {
                $("#" + container).replaceWith(data);
            }
        });
    }

    function UpdateTmdbId(movieId, containerId) {
        SearchTmdb(null, function(newId) {
            ShowTempText(containerId, "Wait...");
            $.ajax({
                url : "@Url.Action("SetMovieTmdbId")" + "/" + movieId,
                type : "POST",
                data : { "tmdbId" : newId },
                success : function(data) {
                    $("#" + containerId).replaceWith(data);
                }
            });
        });
    }

    function ShowImdbIdEditBox(objIn, movieId, container) {
//        alert("hm " + objIn + " hm : " + movieId + " hm : " + container);
        document.editingMovieId = movieId;
        document.editingMovieContainer = container;

        var movieTitle = $("#" + container + " td.movieTitle").text();
        MovieSelectDialog(movieTitle, SetImdbId);
    }

    function SetImdbId(newImdbId) {
        if (newImdbId.length > 6 && document.editingMovieId != null) {
            ShowTempText(document.editingMovieContainer, "Wait...");
            $.ajax({
                "url": "@Url.Action("SetMovieImdbId")" + "/" + document.editingMovieId,
                "type": "POST",
                "data": { "imdbId": newImdbId },
                "success": function (data, text, blah) {
                    $("#" + document.editingMovieContainer).replaceWith(data);
                }
            });
        }
    }

    function ChangeSeenStatus(element, movieId, seen)
    {
        element.onclick = null;
        $(element).unbind("click");
        $(element).text("Wait...");
        var ajaxUrl = "@Url.Action("ChangeSeenStatus")" + "/" + movieId;
        $.ajax({
            "url": ajaxUrl,
            "type": "POST",
            "data": { "seen" : seen },
            "success": function (data, text, blah) {
                if (seen)
                    $(element).text("Film markert som sett!");
                else
                    $(element).text("Du har plutselig ikke sett denne filmen lenger. Magisk!");
            }
        });
    }

    function SetupSpacing() {
        $("#filterFormContainerSpacing").css("height", $("#filterFormContainer").outerHeight(true));
    }

    function SetupTrailerDialog() {
        var jdc = $("#trailerDialog");
        jdc.dialog({
            modal : true,
            position: "center",
            width : "auto",
            height : "auto",
            autoOpen : false,
            close : function () { $("#trailerDialog").empty(); },
            buttons : [ { text: "Close", click: function() { $(this).dialog("close"); } } ]
        });
    }

    function ViewYoutubeTrailer(youtubeId) {
        var jdc = $("#trailerDialog");
        var embedHtml = '<iframe width="640" height="480" src="http://www.youtube.com/embed/' + youtubeId + '?rel=0" frameborder="0" allowfullscreen></iframe>';
        jdc.html(embedHtml);
        jdc.dialog("open");
    }

    $(function () {
        $("#filterForm :input[name|=\"Person\"]").bind("change", function () {
            ClearAllExcept("Person");
            $("#filterForm").submit();
        });
        $("#filterForm :input[name|=\"Genre\"]").bind("change", function () {
            ClearAllExcept("Genre");
            $("#filterForm").submit();
        });
        $("#filterForm :input[name|=\"SortBy\"]").bind("change", function () { $("#filterForm").submit(); });

        $("#dialogContainer form").bind("submit", function() { return false; });

        $(".posterImage").hover(
            function() { 
                var fs = $(this).siblings(".posterFullSize");
                var containerHeight = $(this).closest(".movieContainer").height();
                var imgHeight = fs.height();
                var marginTop = (containerHeight-imgHeight)/2;
                fs.css("margin-top", marginTop);
                fs.css("margin-left", -fs.width() - 25);
                $(this).siblings(".posterFullSize").show('fast');
            },
            function() { 
                $(this).siblings(".posterFullSize").hide('fast');
            }
        );

        $("#searchInputField").select();
        $("#searchInputField").focus();

        $(".movieSourceClicky").bind("click", function () {
            var movieSourceId = $(this).data("moviesourceid");
            var thisElem = $(this);
            if (confirm("Er du sikker på at du vil ignorere denne kilden permanent?")) {
                var ajaxUrl = "@(Url.Action("IgnoreSource"))" + "/" + movieSourceId;
                $.ajax({
                    "url" : ajaxUrl,
                    "type": "POST",
                    "success" : function (data, text, blah) {
                        thisElem.hide();
                    },
                    "error" : function() { 
                        alert("IgnoreSource failed."); 
                    }
                });
            }
        });

        $(".addToToWatch").bind("click", function() {
            var imdbId = $(this).data("imdbId");
            $.post("@Url.Action("AddToWatch", "ToWatch")", { imdbId : imdbId }, function(data) {
                if (data.substring(0, 5) == "error")
                    alert(data);
                else
                    alert("OK");
            });
        });

        $(".showActions").hover(
            function() {
                $(this).children(".movieActions").show("fast");
            },
            function() {
                $(this).children(".movieActions").hide("fast");
            }
        );

        SetupTrailerDialog();

        SetupSpacing();
    });
</script>

<h2>Slutt</h2>
DB kall: @ViewBag.DbCallTime ms

Epidaurus/Views/Movie/MovieListEntry.cshtml
@model Epidaurus.Domain.Entities.Movie
@{
    this.Layout = null;
}
@Html.Partial("Partials/Movie", new Epidaurus.ViewModels.MovieViewModel(Model))

Epidaurus/Views/Movie/TmdbSearch.cshtml
@model IList<Epidaurus.ScannerLib.MovieDataSourceQueryResult>

@if (Model.Count == 0) {
    <div>Ingenting funnet</div>
}
else
{
    <table width="100%">
        <thead>
            <tr><th>Tittel</th><th>År</th><th>ID</th><th>Imdb</th><th>Poster</th></tr>
        </thead>
        @foreach(var result in Model)
        {
            <tr>
                <td><span data-tmdbid="@result.TmdbId" class="clickable tmdbSearchResult">@result.Title</span></td>
                <td>@result.Year</td>
                <td><a target="_blank" href="http://www.imdb.com/title/@result.ImdbId">@result.ImdbId</a></td>
                <td>@result.TmdbId</td>
                <td><img src="@result.Poster" height="100" alt="Poster" /></td>
            </tr>
        }
    </table>
}